#version 430

layout(local_size_x = 256) in;

struct Particle
{
    vec2 position;
    vec2 velocity;
};

struct SpatialEntry
{
    uint particleIndex;
    uint cellKey;
};

layout(std430, binding = 3) buffer predPosBuffer
{
    vec2 predPos[];
};

layout(std430, binding = 4) buffer SpatialLookup
{
    SpatialEntry entries[];
};

uniform uint particleCount;
uniform float smoothRadius;
uniform uint gridWidth;

ivec2 PositionToCellCoord(vec2 point)
{
    vec2 shifted = point + vec2(1.0);
    return ivec2(floor(shifted / smoothRadius));
}



void main()
{
    uint id = gl_GlobalInvocationID.x;

    if(id >= particleCount)
        return;

    ivec2 cell = PositionToCellCoord(predPos[id]);

    uint key = uint(cell.x + cell.y * int(gridWidth));

    entries[id].particleIndex = id;
    entries[id].cellKey = key;
}