#version 430

layout(local_size_x = 256) in;

struct Particle
{
    vec2 position;
    vec2 velocity;
};

layout(std430, binding = 3) buffer PredPosBuffer
{
    vec2 predPos[];
};

layout(std430, binding = 4) buffer CellCounts
{
    uint cellCounts[];
};

layout(std430, binding = 5) buffer CellParticles
{
    uint cellParticles[];
};

layout(std430, binding = 6) buffer OverflowBuffer
{
    uint overflowCounter;
};

uniform uint particleCount;

uniform uint gridWidth;
uniform uint gridHeight;

uniform float smoothRadius;

uniform uint MAX_PARTICLES_PER_CELL;

uniform vec2 worldMin;  
uniform vec2 worldMax;  

ivec2 PositionToCellCoord(vec2 point) // determines what cell the particle is in
{
    vec2 shifted = point - worldMin;
    return ivec2(floor(shifted / smoothRadius));
}

void main()
{
    uint id = gl_GlobalInvocationID.x;

    if(id >= particleCount)
        return;

    ivec2 cell = PositionToCellCoord(predPos[id]);

    if(cell.x < 0 || cell.y < 0)
        return;

    if(cell.x >= int(gridWidth) || cell.y >= int(gridHeight))
        return;

    uint key = uint(cell.x + cell.y * int(gridWidth));

    uint offset = atomicAdd(cellCounts[key], 1); // one more particle in cell

    if(offset >= MAX_PARTICLES_PER_CELL) // if there are too many particles in this cell
    {
        atomicAdd(overflowCounter, 1u);
        return;
    }

    uint index = key * MAX_PARTICLES_PER_CELL + offset;

    cellParticles[index] = id; //add this particle to this cell (or the span of indices representing this cell)
}