#version 430

layout(local_size_x = 256) in;

layout(std430, binding = 1) buffer DensityBuffer
{
    float densities[];
};

layout(std430, binding = 2) buffer PressureBuffer
{
    float pressures[];
};

layout(std430, binding = 3) buffer PredPosBuffer
{
    vec2 predPos[];
};

layout(std430, binding = 4) buffer CellCounts
{
    uint cellCounts[];
};

layout(std430, binding = 5) buffer CellParticles
{
    uint cellParticles[];
};

uniform uint particleCount;

uniform uint gridWidth;
uniform uint gridHeight;

uniform uint MAX_PARTICLES_PER_CELL;

uniform float smoothRadius;
uniform float smoothRadiusSq;
uniform float kernelVolume;

uniform float targetDensity;
uniform float pressureMultiplier;

float kernel(float radius, float dist)
{
    

    float value = max(0.0, radius - dist);

    return value * value * value / kernelVolume;
}

float densityToPressure(float density)
{
    float densityError =
        density - targetDensity;

    return densityError * pressureMultiplier;
}

uniform vec2 worldMin;  
uniform vec2 worldMax;  

ivec2 PositionToCellCoord(vec2 point)
{
    vec2 shifted = point - worldMin;
    return ivec2(floor(shifted / smoothRadius));
}

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if(i >= particleCount)
        return;

    vec2 pos_i = predPos[i];

    ivec2 baseCell =
        PositionToCellCoord(pos_i);

    float density = 0.0;

    for(int y = -1; y <= 1; y++)
    {
        for(int x = -1; x <= 1; x++)
        {
            ivec2 cell = baseCell + ivec2(x, y);

            if(cell.x < 0 || cell.y < 0)
                continue;

            if(cell.x >= int(gridWidth) || cell.y >= int(gridHeight))
                continue;

            uint key = uint(cell.x + cell.y * int(gridWidth));

            uint count = min(cellCounts[key], MAX_PARTICLES_PER_CELL);

            for(uint k = 0; k < count; k++)
            {
                uint pIndex = cellParticles[ key * MAX_PARTICLES_PER_CELL + k ];
            
                vec2 diff = predPos[pIndex] - pos_i;

                float sqrDst = dot(diff, diff);

                if (sqrDst > smoothRadiusSq) continue;

                float dist = sqrt(sqrDst);

                density += kernel(smoothRadius, dist);
            }
        }
    }
    float clampedDensity = max(density, 0.0001);
    densities[i] = clampedDensity;
    pressures[i] = densityToPressure(clampedDensity);
}