#version 430

layout(local_size_x = 256) in;

struct Particle
{
    vec2 position;
    vec2 velocity;
};

layout(std430, binding = 0) buffer Particles
{
    Particle particles[];
};

layout(std430, binding = 1) buffer Densities
{
    float densities[];
};

layout(std430, binding = 2) buffer Pressures
{
    float pressures[];
};

layout(std430, binding = 3) buffer predPosBuffer
{
    vec2 predPos[];
};

uniform uint particleCount;
uniform float smoothRadius;
uniform float targetDensity;
uniform float pressureMultiplier;

float kernel(float radius, float dist)
{
    float volume =
        3.141592 * radius * radius * radius * radius / 2.0;

    float value = max(0.0, radius - dist);

    return value * value * value / volume;
}

float densityToPressure(float density)
{
    float densityError = density - targetDensity;
    float pressure = densityError * pressureMultiplier;//std::max(0.0f, densityError) * pressureMultiplier; // maybe not clamp at 0?
    return pressure;
}

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if(i >= particleCount)
        return;

    vec2 pos_i = predPos[i];

    float density = 0.0;

    for(uint j = 0; j < particleCount; j++)
    {
        vec2 diff =
            predPos[j] - pos_i;

        float dist = length(diff);

        density += kernel(smoothRadius, dist);
    }

    densities[i] = density;
    pressures[i] = densityToPressure(densities[i]);
}