#version 430

layout(local_size_x = 256) in;

struct Particle
{
    vec2 position;
    vec2 velocity;
};

struct SpatialEntry
{
    uint particleIndex;
    uint cellKey;
};

layout(std430, binding = 0) buffer Particles
{
    Particle particles[];
};

layout(std430, binding = 1) buffer Densities
{
    float densities[];
};

layout(std430, binding = 2) buffer Pressures
{
    float pressures[];
};

layout(std430, binding = 3) buffer predPosBuffer
{
    vec2 predPos[];
};

layout(std430, binding = 4) buffer SpatialLookup
{
    SpatialEntry entries[];
};

layout(std430, binding = 5) buffer CellStartBuffer
{
    int startIndices[];
};

uniform uint particleCount;
uniform float smoothRadius;
uniform float targetDensity;
uniform float pressureMultiplier;

uniform uint gridWidth;

float kernel(float radius, float dist)
{
    float volume =
        3.141592 * radius * radius * radius * radius / 2.0;

    float value = max(0.0, radius - dist);

    return value * value * value / volume;
}

float densityToPressure(float density)
{
    float densityError = density - targetDensity;
    float pressure = densityError * pressureMultiplier;//std::max(0.0f, densityError) * pressureMultiplier; // maybe not clamp at 0?
    return pressure;
}

ivec2 PositionToCellCoord(vec2 point)
{
    vec2 shifted = point + vec2(1.0);
    return ivec2(floor(shifted / smoothRadius));
}



void main()
{
    uint i = gl_GlobalInvocationID.x;

    if(i >= particleCount)
        return;

    vec2 pos_i = predPos[i];

    ivec2 baseCell = PositionToCellCoord(pos_i);

    float density = 0.0;

    // 3x3 neighborhood
    for(int y = -1; y <= 1; y++)
    {
        for(int x = -1; x <= 1; x++)
        {
            ivec2 cell = baseCell + ivec2(x, y);

            if(cell.x < 0 || cell.y < 0)
                continue;

            if(cell.x >= int(gridWidth) || cell.y >= int(gridWidth))
                continue;

            uint key = uint(cell.x + cell.y * int(gridWidth));

            int start = startIndices[key];

            if(start == -1)
                continue;

            // iterate linked bucket
            for(uint j = start; j < particleCount; j++)
            {
                if(entries[j].cellKey != key)
                    break;

                uint pIndex = entries[j].particleIndex;

                vec2 diff = predPos[pIndex] - pos_i;

                float dist = length(diff);

                if(dist > smoothRadius)
                    continue;

                density += kernel(smoothRadius, dist);
            }
        }
    }

    densities[i] = density;
    pressures[i] = densityToPressure(density);
}