#version 430

layout(local_size_x = 256) in;

struct Particle
{
    vec2 position;
    vec2 velocity;
};

layout(std430, binding = 0) buffer Particles
{
    Particle particles[];
};

layout(std430, binding = 1) buffer Densities
{
    float densities[];
};

uniform uint particleCount;
uniform float smoothRadius;

float kernel(float radius, float dist)
{
    float volume =
        3.141592 * radius * radius * radius * radius / 2.0;

    float value = max(0.0, radius - dist);

    return value * value * value / volume;
}

void main()
{
    uint i = gl_GlobalInvocationID.x;

    if(i >= particleCount)
        return;

    vec2 pos_i = particles[i].position;

    float density = 0.0;

    for(uint j = 0; j < particleCount; j++)
    {
        vec2 diff =
            particles[j].position - pos_i;

        float dist = length(diff);

        density += kernel(smoothRadius, dist);
    }

    densities[i] = density;
}