#version 430

layout(local_size_x = 256) in;

struct Particle
{
    vec2 position;
    vec2 velocity;
};

layout(std430, binding = 0) buffer Particles
{
    Particle particles[];
};

uniform float dt;
uniform uint particleCount;
uniform vec2 gravity;

uniform vec2 mousePos;
uniform bool mouseDown;
uniform float mouseForceRadius;
uniform float mouseForceStrength;

vec2 calculateMouseForce(uint i)
{
    if (!mouseDown)
        return vec2(0.0f);

    vec2 offset = mousePos - particles[i].position;

    float dist = length(offset);

    if (dist > mouseForceRadius || dist < 1e-5f)
        return vec2(0.0f);

    vec2 dir = offset / dist;

    // Smooth falloff
    float strength =
        1.0f - dist / mouseForceRadius;

    return dir * strength * mouseForceStrength;
}


void main()
{
    uint id = gl_GlobalInvocationID.x;

    if (id >= particleCount)
        return;

    particles[id].velocity += gravity * dt;

    particles[id].velocity += calculateMouseForce(id) * dt;

    particles[id].position +=
        particles[id].velocity * dt;

    ///// boundary collisions
    if (particles[id].position.x < -1.0f) {
            particles[id].position.x = -1.0f;
            particles[id].velocity.x *= -1;
        }
    if (particles[id].position.x > 1.0f) {
            particles[id].position.x = 1.0f;
            particles[id].velocity.x *= -1;
        }
            

    if (particles[id].position.y < -1.0f) {
            particles[id].position.y = -1.0f;
            particles[id].velocity.y *= -1;
        }
    if (particles[id].position.y > 1.0f) {
            particles[id].position.y = 1.0f;
            particles[id].velocity.y *= -1;
        }
}