#version 430

layout(local_size_x = 256) in;

struct Particle
{
    vec2 position;
    vec2 velocity;
};

layout(std430, binding = 0) buffer Particles
{
    Particle particles[];
};

layout(std430, binding = 3) buffer predPosBuffer
{
    vec2 predPos[];
};

uniform float dt;
uniform uint particleCount;

uniform float predictionFactor;

void main()
{
    uint id = gl_GlobalInvocationID.x;

    if (id >= particleCount)
        return;

    predPos[id] = clamp(
    particles[id].position +
    particles[id].velocity * dt * predictionFactor,
    vec2(-0.999),
    vec2(0.999)
);
}